on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@master
        with:
          java-version: 11
          java-package: jdk
      - run: |
          ./gradlew jar
      - if: github.ref == 'refs/heads/master'
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.DEPLOYKEY }} | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan web.sourceforge.net > ~/.ssh/known_hosts
          scp \
              build/libs/SunPKCS11Wrapper.jar \
              ddosolitary@web.sourceforge.net:/home/project-web/ddosolitary-builds/htdocs/
