on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@master
        with:
          java-version: 11
          java-package: jdk
      - run: |
          ./gradlew jar
      - if: github.ref == 'refs/heads/master'
        run: |
          curl -fsS -T build/libs/SunPKCS11Wrapper.jar \
              -u ddosolitary:${{ secrets.BINTRAY_KEY }} \
              -H 'X-Bintray-Package: default' \
              -H 'X-Bintray-Version: default' \
              -H 'X-Bintray-Publish: 1' \
              -H 'X-Bintray-Override: 1' \
              https://api.bintray.com/content/ddosolitary/dev-releases/SunPKCS11Wrapper.jar \
